env: "local" # local, dev, prod

database:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "admin"
  dbname: "bilettm"
  sslmode: "disable"

grpc_server:
  address: "localhost:8082"
  timeout: 4s
  idle_timeout: 120s # If user inactive shut down connection

jwt:
  access_secret_key: 9B2kRpGqWzXv3sA6yZ8Cm5Pd9VfJbE7y
  refresh_secret_key: 5YhNpQsWv3yXuZ9Cm8Pd5Sg7Bj2VfJzA
